[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Pro-level redirects and headers
[[redirects]]
  from = "/admin-login"
  to = "/admin-login"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Pro security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://sqfqlnodwjubacmaduzl.supabase.co; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://sqfqlnodwjubacmaduzl.supabase.co wss://sqfqlnodwjubacmaduzl.supabase.co"

# Asset optimization
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Pro edge functions
[[edge_functions]]
  function = "geolocation"
  path = "/*"

# A/B testing with edge functions
[[edge_functions]]
  function = "ab-testing"
  path = "/*"

# Analytics edge function
[[edge_functions]]
  function = "analytics"
  path = "/*"
  force = true
